const data = {
    status: "success",
    totalResults: 3385,
    results: [
        {
            article_id: "e00972c748ff753df00e4e6e421de666",
            title: "Horoscope Today December 15: ಈ ರಾಶಿಯವರಿಗಿಂದು ಸಮಾಜದಲ್ಲಿ ವಿಶೇಷ ಗೌರವಗಳು ದೊರೆಯುತ್ತವೆ!",
            link: "https://kannada.news18.com/photogallery/astrology/daily-horoscope-today-astrological-predictions-for-december-15-2024-shs-vdd-1945148.html",
            keywords: ["ಭವಿಷ್ಯ"],
            creator: ["News18 Kannada"],
            video_url: null,
            description:
                "ಕೋಡಿ ನಾಮ ಸಂವತ್ಸರ ದಕ್ಷಿಣಾಯನ ಹೇಮಂತ ಋತು ಸೌರ ಮಾಸ ವೃಶ್ಚಿಕ ಚಂದ್ರ ಮಾಸ ಮಾರ್ಗಶಿರ ಶುಕ್ಲ ಪಕ್ಷ ಹುಣ್ಣಿಮೆ ಥ್8ತಿ ಮೃಗಶಿರ ನಕ್ಷತ್ರ ಶುಭ ಯೋಗ ಬಾವ ಕರಣ ರವಿವಾರ ಆಗಿದೆ. ಸುಧಾಮ ಎಚ್.ಎಸ್. ಇವರು ಇಂದಿನ ರಾಶಿಫಲ ತಿಳಿಸಿದ್ದಾರೆ. ಅವರನ್ನು ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಲು ಬಯಸುವವರು 8762085456 ದೂರವಾಣಿ ಸಂಖ್ಯೆಗೆ ಕರೆ ಮಾಡಬಹುದು.",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-15 00:37:37",
            pubDateTZ: "UTC",
            image_url:
                "https://images.news18.com/kannada/uploads/2024/11/WhatsApp-Image-2024-05-13-at-1.09.53-PM-2024-11-fca629f80e9888313b3df0319f55b627-3x2.jpeg",
            source_id: "kannada_news18",
            source_priority: 3093,
            source_name: "News18 Kannada",
            source_url: "https://kannada.news18.com",
            source_icon: "https://i.bytvi.com/domain_icons/kannada_news18.jpg",
            language: "kannada",
            country: ["india"],
            category: ["science"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "c9bfead237959870e0ef329a19ca9023",
            title: "NASA’s Perseverance Rover Reaches the Top Rim of the Jezero Crater - Universe Today",
            link: "https://news.google.com/rss/articles/CBMipgFBVV95cUxNQkdQckZCRU0wR2JhVVJZeldTbldFSUQ5b0EycHM5TkF1a0htdHcyazNxYnYxVXpVcmVCSnVnQ3pBZG9ISW5NYlBMY1FPLWxYaEVEVkRlUmc5OHlWOC1yT2RJa0hNakhRUVVyMFgxV19uSDEtY1MxdkgzWHFMNzhIa05BRjc0d1FidFhlV3gwbDV4R2VtenR0eDRjTEFsTHJUVnRxbjJB?oc=5",
            keywords: null,
            creator: null,
            video_url: null,
            description:
                "NASA’s Perseverance Rover Reaches the Top Rim of the Jezero Crater Universe TodayMars rover makes epic climb to explore some of the oldest rocks in the Solar System Nature.comWorld shaking discovery by NASA; here's what the space agency has disclosed about the red planet Mars The Economic TimesAfter 3.5 months, NASA’s Perseverance Rover climbs atop Jezero Crater Rim on Mars — here’s why it’s significant Down To Earth Magazine10 iconic pictures of Mars clicked by Perseverance rover in 2024 India Today",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-15 00:36:32",
            pubDateTZ: "UTC",
            image_url: null,
            source_id: "google",
            source_priority: 14,
            source_name: "Google News",
            source_url: "https://news.google.com",
            source_icon: "https://i.bytvi.com/domain_icons/google.png",
            language: "english",
            country: ["india"],
            category: ["science"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "909de33d7e1ca9badcb6c243c559112d",
            title: "రూ.2,206 తగ్గిన బంగారం ధర. ఈ లెక్కలు చూస్తే, వెంటనే కొంటారు!",
            link: "https://telugu.news18.com/news/business/gold-prices-drop-today-should-you-buy-22k-and-24k-gold-now-full-analysis-inside-nk-2665238.html",
            keywords: ["బిజినెస్"],
            creator: ["News18 Telugu"],
            video_url: null,
            description:
                "Gold Price: 24 క్యారెట్ల బంగారం లేదా 22 క్యారెట్ల బంగారం.. ఏదైనా సరే కొనాలా వద్దా అనేది ఆలోచించుకునేటప్పుడు మనం చాలా లెక్కలు వేసుకుంటాం. ఇప్పుడు అలాంటి లెక్కలను సింపుల్‌గా చూద్దాం. ఫైనల్‌గా ఇప్పుడు బంగారు నగలు కొనుక్కోవడం ఎందుకు కలిసొస్తుందో తెలుసుకుందాం.",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-15 00:35:07",
            pubDateTZ: "UTC",
            image_url:
                "https://images.news18.com/telugu/uploads/2024/12/Gold-Silver-Price-Today-164179733223-2024-12-90d057a671f85e517264ee9051dbcdca-3x2.jpg",
            source_id: "telugu_news18",
            source_priority: 3892,
            source_name: "Telugu News 18",
            source_url: "https://telugu.news18.com",
            source_icon: "https://i.bytvi.com/domain_icons/telugu_news18.png",
            language: "telugu",
            country: ["india"],
            category: ["business"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "c20d7be230800584b03c8ed08a3aa029",
            title: "Why Is AMU Getting Fewer Foreign Students Now? From 616 To 170, It's A Sharp Fall In 6 Years",
            link: "https://news.abplive.com/education/amu-admissions-sharp-drop-in-foreign-student-enrolment-at-aligarh-muslim-university-see-shocking-stats-1737062",
            keywords: ["education"],
            creator: ["Khaliq Ansari"],
            video_url: null,
            description:
                "AMU Admissions: Aligarh Muslim University (AMU), a prestigious institution renowned for its academic excellence and cultural diversity, is facing a significant drop in the number of international students seeking admission. Once a hub for students from over 30 countries seeking quality education, AMU appears to be losing its appeal among foreign learners. From a total of 616 international students — 462 male and 154 female — enrolling in the academic year 2019-2020, the number is down to just 170 in the current session. This shift has sparked conversations about the factors contributing to this trend and the measures needed to restore its global reputation.According to students, one major reason is the lack of dedicated hostel facilities for foreign students. Many international students prefer to live separately from the general student population, but the absence of specific accommodations discourages them from choosing AMU as their study destination.The AMU administration said they are making efforts to support international students to draw more pupils in the coming future.ALSO READ ON ABP LIVE | India Set To Formalise Informal Learning in Higher Education — All About RPLAMU International Admissions In Last 5 Years2020-21: 3372021-22: 2532022-23: 2122023-24: 1782024-25: 170Challenges Faced By International StudentsAMU once thrived as a global educational hub, attracting students from more than 30 countries. Today, the majority of international students come from Yemen, Indonesia, Bangladesh, and Afghanistan. In its heyday, the campus was a vibrant tapestry of cultures, where students from diverse nations exchanged ideas, explored each other’s cuisines, languages, and traditions, and created an atmosphere of cultural enrichment and camaraderie. This lively exchange not only enhanced the learning environment but also fostered a unique sense of global community on campus.The current lot of 170 students is from 26 countries, including Yemen, Indonesia, Bangladesh, Afghanistan, the United States, Iran, Iraq, Jordan, Nepal, Palestine, Nigeria, Sudan, and Thailand, among others. International students at AMU highlighted a few issues that discourage them from pursuing education at the university. Not wishing to be identified, they said lack of proper accommodations tailored to the needs of international students makes it challenging for them to adjust to campus life. They believe there should be exclusive hostel facilities for international students so they can live in comfort and are able to maintain their lifestyle.Ajju Ishaq, a senior leader of the Samajwadi Party and an alumnus of AMU, attributed the decline in foreign student admissions to broader political and policy changes since 2014. He pointed out that over 10 lakh people have left India in search of better opportunities, and many students now prefer to study abroad due to reduced government support for education.\"Before 2014, AMU attracted students from numerous countries, thanks to government grants and support for international education. However, these initiatives have been discontinued by the current central government,” Ishaq stated.ALSO READ ON ABP LIVE | Bihar BPSC Exam: Paper Leak Allegations Trigger Protests, Boycott; FIR Filed As Chairman Denies ClaimsMeasures Being Taken To Support Foreign Students: AMU AMU administration, however, denies any changes in policies that could hinder the admission or convenience of international students. According to officials, no new regulations have been introduced for international students.Prof. Syed Ali Naveed, Advisor to AMU's International Students' Office, identified multiple reasons behind the decline in international student enrollment These include challenges in the visa process, shifts in the global education landscape, and various socio-economic factors.He emphasised that AMU is actively working to address these issues and has introduced several initiatives aimed at attracting more international students. These measures include enhanced outreach and promotional efforts, support for streamlining visa procedures, and improving facilities to create a more welcoming environment for international students.",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-15 00:33:00",
            pubDateTZ: "UTC",
            image_url:
                "https://feeds.abplive.com/onecms/images/uploaded-images/2024/12/15/2cb6e5b64c3f43c7d45773c8779020ef1734201477315236_original.jpg",
            source_id: "abplive",
            source_priority: 7754,
            source_name: "Abp News",
            source_url: "http://abplive.com",
            source_icon: "https://i.bytvi.com/domain_icons/abplive.jpg",
            language: "english",
            country: ["india"],
            category: ["science"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "167a1351eb17350ee0bbdfd797e7f4bc",
            title: "Utkarsh Sharma on Vanvass, reveals they had doubts for Gadar 2: 'People suggested to make standalone film' | Exclusive",
            link: "https://www.dnaindia.com/bollywood/report-utkarsh-sharma-on-vanvass-reveals-they-had-doubts-for-gadar-2-sunny-deol-ameesha-patel-nana-patekar-anil-sharma-3122448",
            keywords: ["entertainment", "bollywood"],
            creator: ["Simran Singh"],
            video_url: null,
            description:
                "Utkarsh Sharma discusses his upcoming film, Vanvaas, the difference between Sunny Deol and Nana Patekar, the initial doubts they had about Gadar 2 and when we can expect Gadar 3.",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-15 00:32:56",
            pubDateTZ: "UTC",
            image_url:
                "https://cdn.dnaindia.com/sites/default/files/styles/third/public/2024/12/15/2666884-utkarsh-sharma.jpg",
            source_id: "dnaindia",
            source_priority: 18388,
            source_name: "Dna",
            source_url: "https://www.dnaindia.com",
            source_icon: null,
            language: "english",
            country: ["india"],
            category: ["entertainment"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "c86e251bb34e42ff929a44498c85e456",
            title: "OpenAI के रिसर्चर सुचिर बालाजी ने सुसाइड किया:1 दिन पहले मुकदमे में नाम दर्ज हुआ; ChatGPT के 3 खतरे बताकर छोड़ी थी कंपनी",
            link: "https://www.bhaskar.com/career/news/openai-researcher-whistleblower-suchir-balaji-commits-suicide-behind-story-explained-134121106.html",
            keywords: null,
            creator: null,
            video_url: null,
            description:
                "मुझे लगा था कि एआई एक ऐसी चीज है जिसका इस्तेमाल मुश्किल प्रॉब्लम्स को सॉल्व करने में हो सकता है- जैसे बीमारियों का इलाज करना और बुढ़ापे को रोकना। मुझे लगा था कि हम कोई ऐसा साइंटिस्ट बना सकते हैं जो इन दिक्कतों का हल निकालने में मदद करे। फिर जब AI कंपनियों के खिलाफ मुकदमे दायर किए जाने लगे तो मुझे इसके बारे में चिंता होने लगी। ये कहना था आर्टिफिशियल इंटेलिजेंस (AI) फर्म OpenAI के रिसर्चर सुचिर बालाजी का। बीती 26 नवंबर को 26 साल के अमेरिकी भारतीय सुचिर की मौत हो गई है। वह अपने अपार्टमेंट में मृत पाए गए थे। मौत से 1 दिन पहले OpenAI पर मुकदमे में सुचिर के आरोप जोड़े गए यह मामला 14 दिसंबर को चर्चा में आया है। पुलिस को शुरुआती जांच में किसी भी तरह की गड़बड़ी के सबूत नहीं मिले हैं। पुलिस को शक है कि 26 साल के इंडो-अमेरिकन सुचिर ने आत्महत्या की थी। सुचिर तब पहली बार चर्चा में आए थे, जब उन्होंने AI और इसके प्रोटेक्टेड कॉन्टेंट के मिसयूज को लेकर चिंता जताई थी। उन्होंने OpenAI में नैतिक नियमों के उल्लंघन की भी बात कही थी। जबकि वह खुद OpenAI को बनाने वाले लोगों में से एक थे। सुचिर ने ChatGPT बनाने वाली कंपनी OpenAI पर नीतियों के उल्लंघन का आरोप लगाया था। 26 नवंबर को सुचिर का शव मिलने से एक दिन पहले ही OpenAI के खिलाफ दर्ज हुए एक मुकदमे में सुचिर का नाम शामिल किया गया था। मीडिया रिपोर्ट्स के मुताबिक, इसके बाद OpenAI सुचिर की उस फाइल का रिव्यू करने पर राजी हो गई थी, जिसमें उन्होंने कॉपीराइट से जुड़ी चिंताएं जताई थीं। सुचिर AI के जरिए बीमारियों का इलाज, बुढ़ापा दूर करना चाहते थे DeepMind नाम के एक स्टार्टअप ने एक ऐसा AI सॉफ्टवेयर बनाया था, जो स्पेस इनवेडर्स, ब्रेकआउट और पॉन्ग जैसे गेम्स खुद खेल सकता था। इस स्टार्टअप की खबर से सुचिर का AI में इंटरेस्ट जागा। सुचिर AI के जरिए लोगों की समस्याओं का हल निकालना चाहते थे। उन्होंने न्यूयॉर्क टाइम्स से बात करते हुए कहा था, 'मुझे लगा कि हम AI को ऐसा साइंटिस्ट बना सकते हैं जो बीमारियों का इलाज करने और बुढ़ापे को रोकने में मदद कर सके।' इस समय सुचिर बर्कले में कैलिफोर्निया यूनिवर्सिटी में कंप्यूटर साइंस के स्टूडेंट्स थे। उन्होंने न्यूरल नेटवर्क नाम के एक मैथमेटिकल सिस्टम को डेवेलप करने का काम शुरू किया। वह इसे ऐसा नेटवर्क बनाना चाहते थे कि जो खूब सारे डाटा पर एनालिसिस करके कुछ स्किल्स सीख सके। आसान भाषा में कहें तो सुचिर एक ऐसा सॉफ्टवेयर बनाने की कोशिश में थे, जिसमें यह डाटा फीड किया जाए कि अलग-अलग प्रॉब्लम्स को कैसे सॉल्व करना है। उसके बाद वह सॉफ्टवेयर खुद से उन प्रॉब्लम्स को सॉल्व करने की स्किल्स सीख सके। आमतौर पर आज हमारी एक्सेस में जितने भी AI टूल्स हैं, वह यही काम करते हैं। मिसाल के लिए AI हमसे ही सीखकर किसी भी टॉपिक पर इंग्लिश में अच्छी स्टोरी लिखना सीख गया है। हिंदी में काम करना अभी AI सीख रहा है। सुचिर बालाजी ने OpenAI जॉइन किया, ChatGPT बनाने में रही अहम भूमिका इलॉन मस्क ने सैम अल्टमैन के साथ मिलकर 2015 में OpenAI बनाई थी। इसका हेडऑफिस अमेरिका के सैन फ्रांसिस्को में है। यह एक आर्टिफिशियल इंटेलिजेंस (AI) रिसर्च कंपनी है जो ChatGPT जैसे AI टूल्स और सर्विसेज बनाती है। मस्क ने 2018 में कंपनी के बोर्ड से इस्तीफा दे दिया था। मस्क ने OpenAI और अल्टमैन सहित कंपनी के कई और लोगों पर मुकदमा भी दायर किया था। उन्होंने OpenAI के मालिकों पर कॉन्ट्रैक्चुअल एग्रीमेंट्स का उल्लंघन करने का आरोप लगाया था। अगस्त 2024 में सुचिर ने OpenAI की नौकरी छोड़ दी अचानक अगस्त 2024 में सुचिर ने OpenAI छोड़ने का निर्णय लिया। जॉब छोड़ते समय उन्होंने कहा कि जिस टेक्नोलॉजी को डेवेलप करने में उन्होंने मदद की थी, वह फायदे की बजाय नुकसान कर रही है। उन्होंने कहा, अगर आपका भी वही मानना है जो मैं मानता हूं तो आपको भी कंपनी छोड़ देनी चाहिए। मस्क की तरफ से दायर मुकदमे में भी यही कहा गया था कि अल्टमैन और ग्रेग ब्रॉकमैन ने एक ओपन सोर्स, नॉन-प्रॉफिट कंपनी बनाने के लिए मस्क से संपर्क किया था। यह कंपनी इंसानों के फायदे के लिए आर्टिफिशियल इंटेलिजेंस टेक्नोलॉजी डेवलप करने वाली थी। हालांकि OpenAI के मुनाफा कमाने पर फोकस करने से मस्क और OpenAI का समझौता टूट गया। सुचिर ने OpenAI छोड़ने के पीछे क्या चिंताएं जताईं? सुचिर ने 4 साल तक OpenAI के साथ काम किया था। जॉब छोड़ते समय सुचिर ने तीन बड़ी चिंताएं जताई थीं- 1. OpenAI सहित दूसरी फर्म्स ने अपने चैटबॉट और AI टूल्स को ट्रेनिंग देने के लिए अवैध रूप से कंप्यूटर प्रोग्रामर्स, आर्टिस्ट्स, लेखक और न्यूज ऑर्गनाइजेशंस का कॉपीराइट डाटा इस्तेमाल किया है। 2. ChatGPT और इस तरह के दूसरे AI चैटबॉट टूल्स, कॉन्टेंट क्रिएटर्स, बिजनेसेज और इंटरनेट सर्विसेज के लिए खतरा पैदा कर सकते हैं। जबकि AI ने इन्हीं के बनाए डाटा का इस्तेमाल करके ट्रेनिंग ली थी। 3. AI टेक्नोलॉजीज, मौजूदा इंटरनेट सर्विसेज की जगह ले रही हैं। जबकि AI टूल्स अक्सर गलत और मनगढ़ंत जानकारी देते हैं। इससे इंटरनेट बदतर होता जा रहा है। उन्होंने न्यूयॉर्क टाइम्स से बातचीत में बताया था कि GPT-4 जैसे सिस्टम जिस डाटा से ट्रेनिंग लेते हैं, वह उस डाटा की पूरी कॉपी बना लेते हैं। जब पूरा डाटा सॉफ्टवेयर में कॉपी हो जाता है तो OpenAI जैसी कंपनियां सिस्टम को या तो उसी डाटा की कॉपी या फिर पूरी तरह से नए तरीके का आउटपुट देने के लिए प्रशिक्षित कर सकती हैं। उनका कहना था, 'असलियत यह है कि डाटा लेने और फिर आउटपुट देने के बीच में कंपनियां AI को कुछ अलग करने की ट्रेनिंग देती हैं। AI जो आउटपुट देता है वह इनपुट की सटीक कॉपी नहीं हैं, वह पूरी तरह से नया आउटपुट भी नहीं है।' तबसे सुचिर अपने X हैंडल और अपने ब्लॉग पर लगातार ChatGPT के खतरों पर बात करते रहे। अक्टूबर 2024 में X पर अपनी एक पोस्ट में सुचिर ने कहा था, मैं शुरुआत में कॉपीराइट, इंटरनेट के कॉन्टेंट के फेयर यूज वगैरह के बारे में ज्यादा नहीं जानता था। जब AI कंपनियों के खिलाफ मुकदमे दायर किए जाने लगे तो मैं इसके बारे में और चिंतित हुआ। सुचिर के दावों को OpenAI ने नकार दिया था OpenAI ने एक बयान में कहा था, \"हम सार्वजनिक रूप से उपलब्ध डेटा का इस्तेमाल करके, फेयर यूज और नियमों के तहत, कानूनी तरीके से अपने AI मॉडल्स बनाते हैं। हमारा यह सिद्धांत क्रिएटर्स के लिए फेयर है, इनोवेटर्स के लिए जरूरी और अमेरिका में कॉम्पटीटिवनेस यानी प्रतिस्पर्धा के लिए अहम है।' क्या होता है ‘फेयर यूज’ जिसे सुचिर ने AI कंपनियों का झूठा बचाव कहा था किसी की मर्जी से या उसके राइट्स को कानूनी तौर पर खरीदकर किसी का कॉन्टेंट इस्तेमाल करना फेयर यूज कहा जाता है। इस फेयर यूज को लेकर सुचिर ने एक बहुत विचार करने लायक बात कही थी। ऐसा कुछ कहा था जो कॉन्टेंट क्रिएटर्स, अखबार, न्यूज वेबसाइट, लेखकों और आर्टिस्ट्स के लिए बेहद चिंताजनक है। उनका कहना था, AI मॉडल्स में फेयर यूज होने की बात कहना एक ऐसे बचाव की तरह है, जिस पर भरोसा नहीं किया जा सकता। क्योंकि AI को जिस डाटा पर ट्रेनिंग दी जाती है, वह उस डाटा का इस्तेमाल करके ऐसा प्रोडक्ट बना सकते हैं जो उस डाटा को भी टक्कर दे सकता है। ये कुछ ऐसी बात है कि AI, एआर रहमान का म्यूजिक चुराकर उससे मिलता जुलता और उससे भी बेहतर एक म्यूजिक बना दे। फिर जब एआर रहमान उस पर कॉपीराइट स्ट्राइक करें तो यह कह दिया जाए कि यह हमारे AI का अपना बनाया हुआ म्यूजिक है। इसी उदाहरण को कॉन्टेंट क्रिएटर्स, अखबार, न्यूज वेबसाइट, लेखकों और आर्टिस्ट्स भी अपने ऊपर लागू करें तो समझ सकते हैं कि सुचिर की चिंता कितनी जायज थी। यह खबर भी पढ़ें: डिंग का वो ब्‍लंडर जिसने गुकेश को बनाया वर्ल्‍ड चैंपियन:क्‍या है किंग-पॉन एंडगेम, जिसका 55वीं चाल में शिकार बने डिंग लिरेन 12 दिसंबर 2024। सिंगापुर में FIDE शतरंज टूर्नामेंट का फाइनल मुकाबला। भारत के 18 साल के गुकेश और चीन के डिफेंडिंग चैंपियन डिंग लिरेन के बीच पिछले 13 मुकाबलों में स्‍कोर बराबरी पर था। ये मुकाबला भी ड्रॉ होता तो स्‍पीड चेस से वर्ल्‍ड चैंपियन का चुनाव होता। पूरी खबर पढ़ें...",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-15 00:30:53",
            pubDateTZ: "UTC",
            image_url:
                "https://images.bhaskarassets.com/thumb/1000x1000/web2images/521/2024/12/14/edu-cover-14dec_1734183047.gif",
            source_id: "bhaskar_hindi",
            source_priority: 34179,
            source_name: "Bhaskar",
            source_url: "https://www.bhaskar.com",
            source_icon: "https://i.bytvi.com/domain_icons/bhaskar_hindi.png",
            language: "hindi",
            country: ["india"],
            category: ["environment"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "5e3fa3981350a367b5429133fac25d6e",
            title: "Horoscope Today: December 15, 2024",
            link: "https://www.vogue.in/horoscope/collection/horoscope-today-december-15-2024/",
            keywords: ["horoscope"],
            creator: ["Snehaa Khanna Sahgal"],
            video_url: null,
            description:
                "Exit the labyrinth by projecting yourself out of this winding situation. Aquarius, a cycle comes to a close, a new chapter shuts the door on the past, and your inner fires are being winded through the windows of your mind. Look through the tiniest pores and you will find the light you seek. Aries, we [...]",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-15 00:30:12",
            pubDateTZ: "UTC",
            image_url: "https://media.vogue.in/wp-content/uploads/2020/01/Daily-Horoscope.jpg",
            source_id: "vogue",
            source_priority: 2736,
            source_name: "Vogue",
            source_url: "https://www.vogue.com",
            source_icon: null,
            language: "english",
            country: ["india"],
            category: ["entertainment"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "03cc147d5162b64847f6380d3044b244",
            title: "பஞ்சாங்கக் குறிப்புகள் - டிசம்பர் 16 முதல் டிசம்பர் 22 வரை #VikatanPhotoCards",
            link: "https://www.vikatan.com/spiritual/astrology/panchnagam-details-for-the-periods-of-dec-16-to-dec-22",
            keywords: ["astrology"],
            creator: null,
            video_url: null,
            description: null,
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-15 00:30:00",
            pubDateTZ: "UTC",
            image_url:
                "https://gumlet.vikatan.com/vikatan/2024-11-16/ebixgwv8/d5907144-4827-46f3-95b0-ef0f679c7b6c.jpg",
            source_id: "vikatan",
            source_priority: 21554,
            source_name: "Vikatan",
            source_url: "https://www.vikatan.com",
            source_icon: "https://i.bytvi.com/domain_icons/vikatan.png",
            language: "tamil",
            country: ["india"],
            category: ["environment"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "d7fdac39069f6aca7ae7719527e7fe61",
            title: "What's India's next step to be the electronics manufacturing hub of the world?",
            link: "http://economictimes.indiatimes.com/industry/cons-products/electronics/indias-power-surge/articleshow/116335793.cms",
            keywords: null,
            creator: null,
            video_url: null,
            description:
                "The country’s electronics manufacturing sector is set to be strengthened through a major government initiative that will spur the components ecosystem. Experts maintain that India's next step would be to work on increasing the domestic value addition and develop the almost non-existent electronic component supply base. Let's take a closer look at this initiative and what this entails going forward.",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-15 00:30:00",
            pubDateTZ: "UTC",
            image_url:
                "https://img.etimg.com/thumb/msid-116323325,width-1200,height-630,imgsize-584496,overlay-economictimes/articleshow.jpg",
            source_id: "economictimes_indiatimes",
            source_priority: 231,
            source_name: "The Economic Times",
            source_url: "https://economictimes.indiatimes.com",
            source_icon: "https://i.bytvi.com/domain_icons/economictimes_indiatimes.png",
            language: "english",
            country: ["india"],
            category: ["business"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "a4c8869dc38bae84488a150eb7f8f20c",
            title: "Tarot Card Reading For All Zodiac Signs: December 15, 2024",
            link: "https://www.timesnownews.com/astrology/tarot-card-reading-for-all-zodiac-signs-december-15-2024-article-116322250",
            keywords: null,
            creator: ["Dimple V. Mehra"],
            video_url: null,
            description:
                "Tarot Card Reading Today: Start your day with our daily tarot card reading for your zodiac sign and find out what the day has in store for you.",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-15 00:30:00",
            pubDateTZ: "UTC",
            image_url:
                "https://static.tnn.in/thumb/msid-116322280,thumbsize-1853851,width-1280,height-720,resizemode-75/116322280.jpg",
            source_id: "timesnownews",
            source_priority: 2243,
            source_name: "Times Now News",
            source_url: "https://www.timesnownews.com",
            source_icon: "https://i.bytvi.com/domain_icons/timesnownews.png",
            language: "english",
            country: ["india"],
            category: ["science"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
    ],
    nextPage: "1733956596881263020",
};
