const data = {
    status: "success",
    totalResults: 3385,
    results: [
        {
            article_id: "68b496e555a696b766e3e70deb9f6c5c",
            title: '"Czerwone linie" także w Syrii. "Musimy działać bardzo szybko"',
            link: "https://wiadomosci.onet.pl/swiat/czerwone-linie-takze-w-syrii-musimy-dzialac-bardzo-szybko/y58e63q",
            keywords: null,
            creator: null,
            video_url: null,
            description:
                'Szef hiszpańskiego MSZ Jose Manuel Albares stwierdził, że w rozmowach z nowymi przywódcami Syrii konieczne są "czerwone linie". Według niego należy też rozważyć sankcje w celu zapewnienia pokojowej przyszłości Syrii oraz przestrzegania praw człowieka w tym bliskowschodnim kraju.',
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-11 22:48:57",
            pubDateTZ: "UTC",
            image_url:
                "https://ocdn.eu/pulscms-transforms/1/fDpk9kuTURBXy83YjY2NDBiMi04YWRkLTQ1MGUtYjMzZC05ZWY1YzQyZDRhZGYuanBlZ5OVAwAAzRVLzQv7kwXNBLDNAqSTCaZlMDUzY2YG3gABoTAB/rebelianci-swietujacy-upadek-rezimu-baszszara-al-asada.jpg",
            source_id: "wiadomosci",
            source_priority: 37522,
            source_name: "Wiadomosci",
            source_url: "https://wiadomosci.onet.pl",
            source_icon: "https://i.bytvi.com/domain_icons/wiadomosci.png",
            language: "polish",
            country: ["poland"],
            category: ["science", "health"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "4b8b7030d73be7df7ec954e44064b4a7",
            title: "Sols 4389-4390: A Wealth of Ripples, Nodules and Veins",
            link: "https://science.nasa.gov/blog/sols-4389-4390-a-wealth-of-ripples-nodules-and-veins/",
            keywords: ["blogs"],
            creator: [""],
            video_url: null,
            description:
                "Earth planning date: Monday, Dec. 9, 2024 We are continuing to edge our way around the large “Texoli” butte. Much of the bedrock we have been traversing recently looks pretty similar — paler-colored laminated bedrock — but today’s workspace had some interesting features, as did the “drive direction” image, which focuses on the future drive [...]",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-11 22:46:28",
            pubDateTZ: "UTC",
            image_url:
                "https://assets.science.nasa.gov/dynamicimage/assets/science/missions/msl/2024/curiosity-rover-updates/12/https___mars.nasa.gov_msl-raw-images_msss_04387_mcam_4387ML1068360010409270C00_DXXX.jpg?crop=faces%2Cfocalpoint&fit=clip&h=896&w=672",
            source_id: "nasa",
            source_priority: 316,
            source_name: "Nasa",
            source_url: "https://www.nasa.gov",
            source_icon: "https://i.bytvi.com/domain_icons/nasa.png",
            language: "english",
            country: ["united states of america"],
            category: ["science"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "1ed87f9683d884307db7940d9a31538a",
            title: "Thousands of users are unable to access Facebook and Instagram apps",
            link: "https://www.cnn.com/2024/12/11/business/facebook-and-instagram-outage/index.html",
            keywords: null,
            creator: null,
            video_url: null,
            description: null,
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-11 22:45:13",
            pubDateTZ: "UTC",
            image_url: null,
            source_id: "cnn",
            source_priority: 165,
            source_name: "Cnn",
            source_url: "https://edition.cnn.com",
            source_icon: "https://i.bytvi.com/domain_icons/cnn.png",
            language: "english",
            country: ["united states of america"],
            category: [
                "top",
                "sports",
                "technology",
                "business",
                "science",
                "entertainment",
                "health",
                "world",
                "politics",
                "environment",
                "tourism",
                "education",
            ],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: true,
        },
        {
            article_id: "72fba11b7d047bb4527615acf4f8a0e0",
            title: "Pelicot Wore Sunglasses 'to Protect Herself.' No More",
            link: "https://www.newser.com/story/360762/pelicot-wore-sunglasses-to-protect-herself-no-more.html",
            keywords: null,
            creator: ["Jenn Gidman"],
            video_url: null,
            description:
                "Throughout the rape trial of Gisele Pelicot's husband, Dominique Pelicot , and the dozens of other men of sexually assaulting her while she was drugged unconscious, the world has seen the Frenchwoman go through a series of stages—from \"serene grandmother, to anguished and shame-haunted rape victim, to fearful courtroom witness,...",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-11 22:45:05",
            pubDateTZ: "UTC",
            image_url:
                "https://img1-azrcdn.newser.com/image/1578132-11-20241211123310-pelicot-wore-sunglasses-protect-no.jpeg",
            source_id: "newser",
            source_priority: 20689,
            source_name: "Newser",
            source_url: "https://www.newser.com",
            source_icon: "https://i.bytvi.com/domain_icons/newser.png",
            language: "english",
            country: ["united states of america"],
            category: ["science"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "ab0fa256b1dbff0028ee8c5a17667cfd",
            title: "The Arctic Is Lighting Up – and It’s Not the Northern Lights",
            link: "https://scitechdaily.com/the-arctic-is-lighting-up-and-its-not-the-northern-lights/",
            keywords: ["earth", "nasa", "geography", "nasa earth observatory", "arctic"],
            creator: ["Emily Cassidy, NASA Earth Observatory"],
            video_url: null,
            description:
                "The Arctic has seen an increase in human activity, particularly in oil and gas extraction areas, leading to a significant rise in nighttime light as captured by satellite observations. From 1992 to 2013, the Arctic became 5% brighter each year, with industrial activities accounting for most of the artificial light. Nighttime Observations Reveal Human Presence [...]",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-11 22:43:22",
            pubDateTZ: "UTC",
            image_url: "https://scitechdaily.com/images/Nighttime-Lights-Arctic-777x593.jpg",
            source_id: "scitechdaily",
            source_priority: 13386,
            source_name: "Scitechdaily",
            source_url: "https://scitechdaily.com",
            source_icon: "https://i.bytvi.com/domain_icons/scitechdaily.jpg",
            language: "english",
            country: ["world"],
            category: ["science"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "0aaca0f4bdeae2873a56efe4b1c09d97",
            title: "Why it’s OK not to give gifts, World Cup controversy, ‘Conan the Bacterium’: Catch up on the day’s stories",
            link: "https://www.cnn.com/2024/12/11/us/5-things-pm-december-11-trnd/index.html",
            keywords: null,
            creator: null,
            video_url: null,
            description: null,
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-11 22:43:12",
            pubDateTZ: "UTC",
            image_url: null,
            source_id: "cnn",
            source_priority: 165,
            source_name: "Cnn",
            source_url: "https://edition.cnn.com",
            source_icon: "https://i.bytvi.com/domain_icons/cnn.png",
            language: "english",
            country: ["united states of america"],
            category: [
                "top",
                "sports",
                "technology",
                "business",
                "science",
                "entertainment",
                "health",
                "world",
                "politics",
                "environment",
                "tourism",
                "education",
            ],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "cd04214ced2815262909412fea8645c6",
            title: "US scrambles to quell ISIS resurgence in Syria after fall of Assad",
            link: "https://www.cnn.com/2024/12/11/politics/us-scrambles-to-quell-isis-resurgence-syria/index.html",
            keywords: null,
            creator: null,
            video_url: null,
            description: null,
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-11 22:42:26",
            pubDateTZ: "UTC",
            image_url:
                "https://media.cnn.com/api/v1/images/stellar/prod/01-gettyimages-2169320024.jpg?c=16x9&q=h_833%2Cw_1480%2Cc_fill",
            source_id: "cnn",
            source_priority: 165,
            source_name: "Cnn",
            source_url: "https://edition.cnn.com",
            source_icon: "https://i.bytvi.com/domain_icons/cnn.png",
            language: "english",
            country: ["united states of america"],
            category: [
                "top",
                "sports",
                "technology",
                "business",
                "science",
                "entertainment",
                "health",
                "world",
                "politics",
                "environment",
                "tourism",
                "education",
            ],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: true,
        },
        {
            article_id: "ba00651369a48e0b2cafee0369db2c82",
            title: 'تطبيقات قد تتسب بحظر حسابك على "واتس آب" - إرم نيوز',
            link: "https://news.google.com/rss/articles/CBMiYkFVX3lxTE1kTWkwSUFrTEZnWGpoNFdEMEw1VjdWQURoTldkc21iUmlqNmxsSjJ6bGN6bkxZQkQyRHpvdjEyV284dzI2OWlETUNXTlFjUmM1SmtYV0hneDdTUXBHOEVRWmFn0gFiQVVfeXFMTWRNaTBJQWtMRmdYamg0V0QwTDVWN1ZBRGhOV2RzbWJSaWo2bGxKMnpsY3puTFlCRDJEem92MTJXbzh3MjY5aURNQ1dOUWNSYzVKa1hXSGd4N1NRcEc4RVFaYWc?oc=5",
            keywords: null,
            creator: null,
            video_url: null,
            description:
                'تطبيقات قد تتسب بحظر حسابك على "واتس آب" إرم نيوزاحذفهم من التليفون بسرعة.. تحذير من 5 تطبيقات مشهورة بتسرق صورك ورسائل واتساب http://www.zahraa.mr/nكيف تحمي هاتفك من تهديدات تطبيقات التجسس؟ الموجز العربيتجنب التطبيقات غير الرسمية على واتس آب لحماية بياناتك صحيفة السوسنة الأردنيةتطبيقات التجسس: خطر متزايد على خصوصية الهواتف الذكية أخبارنا المغربية',
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-11 22:42:11",
            pubDateTZ: "UTC",
            image_url: null,
            source_id: "google",
            source_priority: 14,
            source_name: "Google News",
            source_url: "https://news.google.com",
            source_icon: "https://i.bytvi.com/domain_icons/google.png",
            language: "arabic",
            country: ["saudi arabia"],
            category: ["technology", "science"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "29d77513ef13b4193e7662dab2b95b10",
            title: "В глубинах космоса найден молодой двойник Млечного Пути",
            link: "https://www.pravda.ru/news/science/2147962-young-milky-way/",
            keywords: ["наука"],
            creator: null,
            video_url: null,
            description:
                'Астрономы из Wellesley College представили удивительные фотографии галактики, которая напоминает юный Млечный Путь.Снимки, сделанные с помощью телескопа NASA James Webb, открывают взору галактику "Firefly Sparkle" ("Искра светлячков"), состоящую из 10 звёздных кластеров, сформировавшихся в разное время.Рождение звёздной системыЭта галактика начала формироваться всего через 600 миллионов лет после Большого взрыва, примерно в тот же период, когда зарождался наш Млечный Путь. Кластеры звёзд, окружающие галактику, напоминают светлячков в летней ночи, создавая впечатляющую картину ранней Вселенной.',
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-11 22:38:00",
            pubDateTZ: "UTC",
            image_url: "https://img.pravda.ru/image/preview/article/9/6/2/2147962_sq.jpeg",
            source_id: "pravda_ru",
            source_priority: 44533,
            source_name: "Pravda",
            source_url: "https://english.pravda.ru",
            source_icon: "https://i.bytvi.com/domain_icons/pravda_ru.png",
            language: "russian",
            country: ["russia"],
            category: ["science"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
        {
            article_id: "4bf1d5e541ca578faebdf9b50de482eb",
            title: "Jared Isaacman on U.S. space competitiveness: ‘We can’t be second’",
            link: "https://spacenews.com/jared-isaacman-on-u-s-space-competitiveness-we-cant-be-second/",
            keywords: [
                "jared isaacman",
                "news",
                "space force",
                "military",
                "civil",
                "commercial",
                "nasa",
            ],
            creator: ["Sandra Erwin"],
            video_url: null,
            description:
                "Trump’s pick to lead NASA says the private sector has to lead the way in innovationThe post Jared Isaacman on U.S. space competitiveness: ‘We can’t be second’ appeared first on SpaceNews.",
            content: "ONLY AVAILABLE IN PAID PLANS",
            pubDate: "2024-12-11 22:36:36",
            pubDateTZ: "UTC",
            image_url:
                "https://i0.wp.com/spacenews.com/wp-content/uploads/2024/12/Screenshot-2024-12-11-at-2.47.55%20PM-e1733956342623.png?fit=300%2C171&ssl=1",
            source_id: "spacenews",
            source_priority: 27510,
            source_name: "Space News",
            source_url: "https://spacenews.com",
            source_icon: "https://i.bytvi.com/domain_icons/spacenews.png",
            language: "english",
            country: ["united states of america"],
            category: ["technology", "science"],
            ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
            ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
            ai_org: "ONLY AVAILABLE IN CORPORATE PLANS",
            duplicate: false,
        },
    ],
    nextPage: "1733956596881263020",
};
